
name: CI/CD with Render

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Run Tests (Optional, adjust as per your stack)
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Run tests
      run: |
        if [ -f package.json ]; then
          npm test
        fi

    # Step 3: Deploy to Render
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{"clearCache":true}' \
          https://api.render.com/v1/services/<YOUR-SERVICE-ID>/deploys
